name: PistonCrusher
main: org.example.PistonCrusherPlugin
version: ${project.version}
api-version: 1.20
author: Cobbleworks
website: https://github.com/Cobbleworks/Piston-Crusher-Plugin
commands:
  pistoncrusher:
    description: Configure the PistonCrusher (Blacklist, Multiplier)
    usage: /pistoncrusher <blacklist|multiplier>
    permission: pistoncrusher.admin
    permission-message: You do not have permission to use this command.
